version: '3.8'

services:
  # Servicio frontend (React)
  frontend:
    image: igrowker/i004-crewland-front-dev-image
    container_name: crewland-frontend
    ports:
      - "80:3000" 
    volumes:
      - /app/node_modules
    environment:
      - BACKEND_REFERENCE=${BACKEND_REFERENCE} # Pasar la referencia del backend como variable de entorno
    command: >
      sh -c "
      sed -i \"s|http://localhost:3000|${BACKEND_REFERENCE}|g\" /app/src/server.config.ts &&
      npm run dev
      "
    networks:
      - crewland-network

networks:
  crewland-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local