services:
  frontend:
    build:
      context: ../../i004-pawsome-front
      dockerfile: Dockerfile
      target: dev
    networks:
      - app-network
    ports:
      - "5173:5173"
    volumes:
      - ../../i004-pawsome-front:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    profiles:
      - dev
      - prod

  backend:
    build:
      context: ../../i004-pawsome-back
      dockerfile: Dockerfile
      target: dev
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - ../../i004-pawsome-back:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      MONGO_URI: ${URI}
    profiles:
      - dev
      - prod
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    profiles:
      - dev
      - prod
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
