services:
  frontend:
    build:
      context: ../../i004-pawsome-front
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "5173:5173"
      - "80:80"
    volumes:
      - ../../i004-pawsome-front:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    profiles:
      - dev

  backend:
    build:
      context: ../../i004-pawsome-back
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - ../../i004-pawsome-back:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      MONGO_URI: ${URI}
    profiles:
      - dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    profiles:
      - dev
    networks:
      - app-network

volumes:
  pg_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
